name: 'Algosec Risk Analysis action'
description: 'This GitHub Action runs Algosec Risk Analysis against an Infrastructure-as-Code repository. This Action performs static security analysis of Terraform.'
author: 'alon.noy@algosec.com'
runs:
  using: 'node16'
  main: 'dist/index.js'
