name: 'Release'
on:
  pull_request:
    branches:
      - 'develop'
jobs:
  release:
   runs-on: ubuntu-latest
   steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Determine Version
      id: determine_version
      uses: paulhatch/semantic-version@v4.0.2
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        namespace: develop
        change_path: "."
        format: "${major}.${minor}.${patch}-prerelease${increment}"
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v${{steps.determine_version.outputs.major}}.${{steps.determine_version.outputs.minor}}.${{steps.determine_version.outputs.patch}}-prerelease.${{steps.determine_version.outputs.increment}}"
        release_name: "v${{steps.determine_version.outputs.major}}.${{steps.determine_version.outputs.minor}}.${{steps.determine_version.outputs.patch}}-prerelease.${{steps.determine_version.outputs.increment}}"
        draft: false
        prerelease: true
    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
